### ISSUE TITLE
show patch dates

### ISSUE THREAD

**Issue by aeosynth** [arthurazs/dotapatch#39]
would be useful to gauge when the next patch is coming out

**Comment by arthurazs** [comment]
What would be the best place to have this information?
The [README](https://github.com/arthurazs/dotapatch/blob/master/README.rst) and the [main page](https://arthurazs.github.io/dotapatch/) ([source](https://github.com/arthurazs/dotapatch/blob/gh-pages/index.html)) maybe?

**Comment by aeosynth** [comment]
i was thinking the main page and each patch page:

> Gameplay Update 7.17 (10/06/2018)
